name: Alt_You

on:
  workflow_dispatch:
  schedule:
     - cron: '20 0-15/2 * * *'
  watch:
    types: Youth_Read
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_READ: ${{ secrets.YOUTH_READ }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【Alt_You】'
        if: env.YOUTH_READ
        run: |
          node Scripts/Alt_You.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ }}
