name: Alts
on:
  workflow_dispatch:
  #schedule:
  #  - cron: '*/30 0-11/1 * * *'
jobs:
  build:
    runs-on: macos-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/IooTelecom/-.git ~/-
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/-
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json

      - name: '【Alts】'
        run: |
          cd ~/-/Scripts   
          node Alts.js
       env:
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
