name: Alt_You

on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '30 10 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/IooTelecom/-.git ~/js
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/js
          npm install
          npm install cron
          npm install request
          npm install md5-node
          npm install 'got' --save-dev
      - name: '运行 【Alt_You】'
        run: |
          cd ~/js   
          #node Scripts/youth1.js
      - name: '运行 【Alt_You】'
        run: |
          cd ~/js   
          node Scripts/Alt_You.js
          env:
          YOUTH_READ: ${{ secrets.YOUTH_READ }}
